In [4]:
#Question 1
import numpy as np
array = np.array([10,20,30,40,50])
add = 0
for sum in array:
    add += sum
print(add)

150


In [5]:
#Question 2
array = np.array([10,20,40,3,2,100])
large = np.max(array)
print(large)

100


In [7]:
#Question 3
a = np.array([2, 6, 1, 9, 10, 3, 27])
count = []
for i in a:
    if i in range(5,11):
        count.append(i)
print(count)
    

[6, 9, 10]


In [14]:
#Question 4
def rotate(arr, d, n):
    d = d % n  # Handle cases where d > n
    arr[:] = arr[d:] + arr[:d]  # Using slicing to rotate

# Example Usage
arr = [1, 2, 3, 4, 5, 6, 7]
d = 2
n = len(arr)

rotate(arr, d, n)
print("Rotated array:", arr)


Rotated array: [3, 4, 5, 6, 7, 1, 2]


In [23]:
#Question 5
def slice(arr,k):
    k = k % len(arr)
    return np.concatenate((arr[k:],arr[:k]))
a = np.array([2, 6, 1, 9, 10, 3, 27])
k=1
result = slice(a,k)
print(result)

[ 6  1  9 10  3 27  2]


In [33]:
#Question 6
def calculate(arr,n):
    multi = 1
    remainder = 0
    for i in arr:
        multi *= i
        remainder = multi % n
    return f"remainder is {remainder} and multiplication is {multi}"
arr = [100, 10, 5, 25, 35, 14]
n = 11
sum = calculate(arr,n)
print(sum)

remainder is 9 and multiplication is 61250000


In [35]:
#Question 7
num1 = np.array([[1,2],[3,4]])
num2 = np.array([[5,6],[7,8]])
result = np.multiply(num1,num2)
print(result)

[[ 5 12]
 [21 32]]


In [37]:
#Question 8
num1 = np.array([[1,2],[3,4]])
result = np.transpose(num1)
print(f"Original : ")
print(num1)
print(f"transpose : ")
print(result)

Original : 
[[1 2]
 [3 4]]
transpose : 
[[1 3]
 [2 4]]


In [3]:
#Question 9
import numpy as np
array= np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
arr = np.arange(9).reshape(3,3)
print("Original Array")
print("/n")
print(array)
print("\nModified array")
print(arr[:,[1,0,2]])

Original Array
/n
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [4]:
#Question 10
array= np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
arr = np.arange(9).reshape(3,3)
print("Original Array")
print("/n")
print(array)
print("\nModified array")
print(arr[[1,0,2],:])

Original Array
/n
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [13]:
#Question 11
arr1= np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
arr2= np.array([[9, 10, 11],[12, 13, 14],[15, 16, 17]])
sum = np.add(arr1,arr2)
print(f"Sum Of Two matrix is : ")
print(sum)

Sum Of Two matrix is : 
[[ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [14]:
#Question 12
arr1= np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
arr2= np.array([[9, 10, 11],[12, 13, 14],[15, 16, 17]])
sum = np.multiply(arr1,arr2)
print(f"Multiplication Of Two matrix is : ")
print(sum)

Multiplication Of Two matrix is : 
[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [15]:
#Question 13
arr1= np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
arr2= np.array([[9, 10, 11],[12, 13, 14],[15, 16, 17]])
sum = np.dot(arr1,arr2)
print(f"product of matrix is : ")
print(sum)

product of matrix is : 
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [17]:
#Question 14
arr1= np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
arr2= np.array([[9, 10, 11],[12, 13, 14],[15, 16, 17]])
sum = np.add(arr1,arr2)
sum1 = np.subtract(arr1,arr2)
print(f"Addition of matrix is : ")
print(sum)
print(f"Subtraction of matrix is : ")
print(sum1)

Addition of matrix is : 
[[ 9 11 13]
 [15 17 19]
 [21 23 25]]
Subtraction of matrix is : 
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [19]:
#Question 15
arr1= np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
trans = np.transpose(arr1)
print(trans)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [33]:
#Question 16
import random
# def matrix(arr,n):
#     arr = np.arange(9).reshape(n,n)
#     return arr
def generate_matrix(n):
    arr = np.random.randint(1,10,(n,n))
    return arr
# arr = []
n = int(input("Enter Matrix Size"))
#matrix(arr,n)
matrix = generate_matrix(n)
print(matrix)

Enter Matrix Size 5


[[4 4 7 6 6]
 [6 2 4 2 2]
 [6 3 7 5 3]
 [9 9 4 1 2]
 [7 2 4 3 8]]


In [36]:
#Question 17
list = [12.23, 13.32, 100, 36.32]
numpy = np.array(list)
print(f"Original list = {list}")
print(f" One-dimensional NumPy array: {numpy}")

Original list = [12.23, 13.32, 100, 36.32]
 One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [38]:
#Question 18
def matrix(arr):
    arr = np.arange(2,11).reshape(3,3)
    return arr
arr = []
matrix(arr)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
#Question 19


In [40]:
#Question 20
def matrix(arr):
    arr = np.arange(12,38)
    return arr
arr = []
matrix(arr)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [43]:
#Question 21
arr = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])
reverse = arr[::-1]
print("Original Array")
print(arr)
print("Reverse Array")
print(reverse)

Original Array
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse Array
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [46]:
#Question 22
arr = [1, 2, 3, 4]
result = np.array(arr, dtype = "float")
print("Original ")
print(arr)
print(" Array converted to a float type:")
print(result)

Original 
[1, 2, 3, 4]
 Array converted to a float type:
[1. 2. 3. 4.]


In [19]:
#Question 23
import numpy as np
import random
def create_matrix():
    matrix = np.zeros((8, 8), dtype=int) 
    matrix[1::2, ::2] = 1 
    matrix[::2, 1::2] = 1  
    return matrix
matrix = create_matrix()
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#Question 24
list = [1,2,3,4,5,6,7,8]
tuple = ((8,4,6),(1,2,3))
print("List to array")
arr1 = np.array(list)
print(arr1)
print("  ")
print("Tuple to array")
arr2 = np.array(tuple)
print(arr2)

List to array
[1 2 3 4 5 6 7 8]
  
Tuple to array
[[8 4 6]
 [1 2 3]]


In [23]:
#Question 25
arr = np.array([10,20,30])
arr2 = np.array([40,50,60,70,80])
new_arr = np.append(arr,arr2)
print(f"Original Array : {arr}")
print(f"After append values to the end of the array: {new_arr}")

Original Array : [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80]


In [25]:
#Question 26
arr = np.array([0,10,20,40,60])
arr2 = np.array([0,40])
result = np.isin(arr,arr2)
print(f" Compareeach elementof array1 and array : {result}")
        

 Compareeach elementof array1 and array : [ True False False  True False]


In [33]:
#Question 27
arr = np.array([10, 10, 20, 20, 30, 30])
unique = np.unique(arr)
print(f"Original arr : {arr}")
print(f" Unique elements of the above array : {unique}")

arr2 = np.array([[1,1],[2,3]])
unique = np.unique(arr2)
print(f"Original arr : ")
print(arr2)
print(f" Unique elements of the above array : {unique}")

Original arr : [10 10 20 20 30 30]
 Unique elements of the above array : [10 20 30]
Original arr : 
[[1 1]
 [2 3]]
 Unique elements of the above array : [1 2 3]


In [47]:
#Question 28 
Array1 = np.array([0, 10, 20, 40, 60, 80])
Array2 = np.array([10, 30, 40, 50, 70])
unique_in_1 = Array1[~np.isin(Array1,Array2)]
unique_in_2 = Array2[~np.isin(Array2,Array1)]
unique = np.unique(np.concatenate((unique_in_1,unique_in_2)))
print("Set difference between two arrays : ")
print(unique)

Set difference between two arrays : 
[ 0 20 30 50 60 70 80]


In [45]:
#Question 29
Array1 = np.array([0, 10, 20, 40, 60, 80])
Array2 = np.array([10, 30, 40, 50, 70])
unique = np.unique(np.concatenate((Array1,Array2)))
print(unique)

[ 0 10 20 30 40 50 60 70 80]


In [50]:
#Question 30
Original = np.array([1,2,3,4])
concate_2 = np.concatenate([Original]*2)
concate_3 = np.concatenate([Original]*3)
print("Original array : ")
print(Original)
print("Repeating 2 times :")
print(concate_2)
print("Repeating 3 times :")
print(concate_3)

Original array : 
[1 2 3 4]
Repeating 2 times :
[1 2 3 4 1 2 3 4]
Repeating 3 times :
[1 2 3 4 1 2 3 4 1 2 3 4]


In [52]:
#Question 31
Original = np.array([1,2,3,4])
max = np.max(Original)
min = np.min(Original)
print(f"Maximam : {max}")
print(f"Minimum : {min}")

Maximam : 4
Minimum : 1


In [62]:
#Question 32
arr = np.array([1,2,3,4,5,6,7,8,9])
print("9 rows and 0 columns")
print(arr.shape)
print("3 rows and 3 columns")
arr_2D = arr.reshape(3,3)
print(arr_2D)
print("New Shape")
print(arr_2D.shape)

9 rows and 0 columns
(9,)
3 rows and 3 columns
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New Shape
(3, 3)


In [65]:
#Question 33
arr = np.array([1,2,3,4,5,6])
print("Reshape array to (3,2)")
print(arr.reshape(3,2))
print("Reshape array to (2,3)")
print(arr.reshape(2,3))

Reshape array to (3,2)
[[1 2]
 [3 4]
 [5 6]]
Reshape array to (2,3)
[[1 2 3]
 [4 5 6]]


In [70]:
def create_matrix(arr):
    arr = np.random.randint(2,3,(3,5))
    concate = np.concatenate([arr]*2)
    return concate
arr = []
result = create_matrix(arr)
print(result)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
